name: storyapp_intermediate
description: A new Flutter project.


publish_to: 'none' 













version: 1.0.0+1

environment:
  sdk: '>=3.1.1 <4.0.0'







dependencies:
  camera: ^0.10.5+5
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.4.1
  go_router: ^11.1.2
  http: ^1.1.0
  image: ^4.1.3
  image_cropper: ^5.0.0
  image_picker: ^1.0.4
  json_annotation: ^4.8.1
  shared_preferences: ^2.2.1

dev_dependencies:
  bloc_test: ^9.1.3
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.5
  json_serializable: ^6.7.1



flutter:

  
  
  
  uses-material-design: true
  
  assets:
    - assets/logo/
    - assets/image/
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
